### PR TITLE
Fix #11639 Bug with the MainBackground Color

### PR DESCRIPTION
**Pull request by madhuracj**

### CODE REVIEW

**Comment by lem9** [comment]
This does not seem to work for me. layout.inc.php is loaded after config.inc.php, so $cfg['MainBackground'] in config.inc.php is not used.

**Comment by PineSmokes** [comment]
This definitely works, I tested it minutes after he fixed it your issue is somewhere else.  Download a theme and try applying these changes to it, that way the theme is fresh.  I'm not sure if you've been messing with the theme or not but it's possible something is out of place.  I'm trying to upload my theme, it's based off the metro theme but it's perfect and dark.  A PhpMyAdmin Dark Theme is so necessary not sure why nobody made one until I just did last night :)

**Comment by PineSmokes** [comment]
I think I kept clicking the wrong button, new pull request, sorry if I repoen this?  If I did that was an accident still trying to figure out how to submit my theme :)

**Comment by lem9** [comment]
I'm trying with the metro theme + Madhura's current patch, changing this in config.inc.php:
````
$cfg['MainBackground'] = '#111111';
````
and it has no effect, due to the file loading order as I wrote above.

**Comment by PineSmokes** [comment]
Did you remove the two lines from the common.css.php?  If you forget to remove the "color: #444;" and the "background: #fff;" you won't see anything change EVER.  Those lines need to be removed.

Go download mine and let me know if it works I fixed everything all night :)
https://github.com/PineSmokes/Dark-PhpMyAdmin-Theme

**Comment by madhuracj** [comment]
@lem9  
I thought the theme related settings are changed in layout.inc.php rather than config.inc.php. Metro theme was ignoring its own layout.inc.php and this is what is fixed here. Config loading order as you pointed out needs to be changed in phpMyAdmin.

**Comment by lem9** [comment]
@madhuracj I agree with your comment, but this means that we don't need to change the config loading order.

**Comment by madhuracj** [comment]
ok

**Comment by PineSmokes** [comment]
So I can't locate the hard set value for the LAST thing I want to change on the entire page.  The hex color comes out to #F2F2F2 if you press CTRL + U to get the source while viewing your PhpMyAdmin page, it's the Recents and Favorites button background, no matter what I do it will not change, it must be hard coded somewhere can you locate it?

**Comment by madhuracj** [comment]
@PineSmokes 
Assuming that you are editing the metro theme, see https://github.com/phpmyadmin/themes/blob/master/metro/css/navigation.css.php#L445

**Comment by PineSmokes** [comment]
Wow you're so quick and perfect hah, you're my savior no joke :)

**Comment by PineSmokes** [comment]
How do I go about adding my completed theme to the list?  It includes the Metro Light theme alongside the new Metro Dark theme I made, had to include the original because when I delete the original it seems to mess up the font, so I decided to leave it as a bonus and to hopefully keep the font the way it they had it in the original metro theme.
https://github.com/PineSmokes/Dark-PhpMyAdmin-Theme/releases/tag/1.0

**Comment by lem9** [comment]
@madhuracj Do you think it would be a good idea to stop using "cfg" for theme-related directives? The more I think about that, the more I find this usage awkward and counter-intuitive. For me, "cfg" refers to config.inc.php and libraries/config.default.php. I know that the doc says "See themes/themename/layout.inc.php." for these directives, but still.

**Comment by madhuracj** [comment]
@lem9 I tend to agree. So, we will have to do changes in all the themes and in the documentation. What do we call the new configuration array? $cfgTheme?

**Comment by lem9** [comment]
We might talk to the rest of the team before deciding about the details; maybe in the next IRC meeting?
By the way, I would wait for 4.6 for these changes.

**Comment by madhuracj** [comment]
Yeps, sounds good

**Comment by lem9** [comment]
I'll update the wiki.

**Comment by madhuracj** [comment]
@PineSmokes The best way to go about this would be to fork https://github.com/phpmyadmin/themes, create a feature branch, add your new theme and make a pull request.

**Comment by PineSmokes** [comment]
Thanks for the explanation :)

**Pull request merged**
