### PR TITLE
Black carde

### PR DESCRIPTION
**Pull request by AppCarde**
I've been working on a theme to help me with projects and in my spare time I've been perfecting that.
For PhpMyAdmin 5.0, 5.1 and current version 5.2
[BlackCarde.zip](https://github.com/phpmyadmin/themes/files/8455841/BlackCarde.zip)
MVhJtBbO

### CODE REVIEW

**Comment by williamdes** [comment]
Hi @AppCarde
Can you put the contents of your theme in a PR?

**Comment by AppCarde** [comment]
> Hi @AppCarde Can you put the contents of your theme in a PR?

Forgive me, Github is almost new language for me. I thought it was already in Pull Request.

**Comment by williamdes** [comment]
> > Hi @AppCarde Can you put the contents of your theme in a PR?
> 
> Forgive me, Github is almost new language for me. I thought it was already in Pull Request.

No worries then, you indeed already did open a PR but the contents are not your theme. I will open one with the contents for you :)

**Comment by williamdes** [comment]
Hi,
Please check https://github.com/phpmyadmin/themes/pull/72 where I did unzip your theme into git

**Comment by AppCarde** [comment]
> Oi, Por favor, verifique #72 onde eu descompactei seu tema no git

thankful

**Pull request closed without merging**
