### PR TITLE
Update several themes for phpMyAdmin 4.7

### PR DESCRIPTION
**Pull request by ibennetch**
I've attempted to update several common themes for phpMyAdmin 4.7.

### CODE REVIEW

**Comment by ibennetch** [comment]
Chances are good that I've missed some minor detail that needs to be fixed, but they should be pretty compatible with 4.7.

**Comment by ibennetch** [comment]
If https://github.com/phpmyadmin/phpmyadmin/pull/13006 is merged, we should make a similar change to these themes.

**Comment by nijel** [comment]
Good job!

**Comment by nijel** [comment]
I'm not going to release them right now, as I've merged phpmyadmin/phpmyadmin#13006, so these themes should be probably adjusted as well.

**Comment by nijel** [comment]
Adjusted that in a872274f34

**Comment by nijel** [comment]
I've released the themes just now: https://www.phpmyadmin.net/themes/

**Pull request merged**
