### PR TITLE
MHN 1.0

### PR DESCRIPTION
**Pull request by khadkamhn**
New flat theme for phpMyAdmin 4.6.3

### CODE REVIEW

**Comment by nijel** [comment]
Thanks for your contribution, the theme really looks good!. I've noticed that the ``css/mhn.img.php`` is vulnerable to XSS on all parameters it accepts from GET, you should really filter what is accepted there. Besides that I think it's ready to be merged and released.

**Comment by khadkamhn** [comment]
Hello @nijel 
I have updated that file with fixed that xss security issues.

**Comment by nijel** [comment]
Thanks, I'll get back to this next week.

Meanwhile, is the code commented out intentionally? Maybe it's better to remove it then: https://scrutinizer-ci.com/g/phpmyadmin/themes/inspections/ce19a4bc-266c-4f73-a7f9-632b9b33569e/issues/files/mhn/css/common.css.php?status=new&selectedLabels%5B0%5D=2&orderField=path&order=asc&honorSelectedPaths=0

**Comment by nijel** [comment]
Oops looks like I've completely forgotten on this...

**Comment by nijel** [comment]
Thanks for contribution and sorry that it took so long to merge. The theme is now online at https://www.phpmyadmin.net/themes/

**Comment by ibennetch** [comment]
This is really beautiful. Nice work.

It doesn't look like it is compatible with master (which will become 4.7), but hopefully it can be updated before 4.7 is actually released.

**Comment by nijel** [comment]
Yes, most themes will need updates for 4.7 - at least regenerate sprites data and handle odd/even rows fully in css.

**Comment by nijel** [comment]
Theme is now available on our [demo server](https://www.phpmyadmin.net/try/). It will need some adjustments to work on the master branch (upcoming 4.7.0).

**Comment by nijel** [comment]
@ibennetch has adjusted this theme to work on 4.7.0 (see https://github.com/phpmyadmin/themes/pull/20), but he had some troubles manipulating with the icons, see our mailing list: https://lists.phpmyadmin.net/pipermail/developers/2017-February/019893.html

**Comment by khadkamhn** [comment]
Thank you for fixing bug for this theme.
I have added missing png file.

**Comment by nijel** [comment]
Thanks, merged to themes repo.

**Pull request merged**
