### PR TITLE
new theme DarkOrange V5.2

### PR DESCRIPTION
**Pull request by abolfazlrvn**
DarkOrange theme for phpMyAdmin V5.2

### CODE REVIEW

**Comment by williamdes** [comment]
Closing this one as it does not make sense :)
Please have a look to: https://github.com/phpmyadmin/themes#how-to-contribute

But for now you do not need to open a pull-request, #85 is already open (as an issue) for your theme.

**Comment by williamdes** [comment]
Duplicate of #85

**Comment by abolfazlrvn** [comment]
> Duplicate of #85
I thought I needed to make a pool request, thanks for your advice. :D

**Comment by abolfazlrvn** [comment]
> Closing this one as it does not make sense :) Please have a look to: https://github.com/phpmyadmin/themes#how-to-contribute
> 
> But for now you do not need to open a pull-request, #85 is already open (as an issue) for your theme.

I think it's not approved yet, right?

**Comment by williamdes** [comment]
> I think it's not approved yet, right?

Do not worry, things are a bit slow on this repository. We will take care of your theme to test it and build it

**Comment by abolfazlrvn** [comment]
> Do not worry, things are a bit slow on this repository. We will take care of your theme to test it and build it

I can make much more beautiful themes, I made this theme very quickly and I will definitely have an update later. Thank you very much for your response

**Comment by williamdes** [comment]
> > Do not worry, things are a bit slow on this repository. We will take care of your theme to test it and build it
> 
> I can make much more beautiful themes, I made this theme very quickly and I will definitely have an update later. Thank you very much for your response

Could you try to see if you can have the normal workflow running on your workstation so we can have some of your help on fixing some themes ?
https://github.com/phpmyadmin/themes#how-to-contribute

**Pull request closed without merging**
