### PR TITLE
Blueberry Theme - phpMyadmin v5.2

### PR DESCRIPTION
**Pull request by movahhedi**
# Blueberry PHPMyAdmin Theme

[Blueberry](https://github.com/movahhedi/blueberry-pma-theme) is a modern dark theme for PHPMyAdmin, based on "pmahomme" theme (The default theme in PHPMyAdmin).

Developed by **Shahab Movahhedi**
- Site: [shmovahhedi.com](https://shmovahhedi.com)
- Email: [dev@shmovahhedi.com](mailto:dev@shmovahhedi.com)
- GitHub: [@movahhedi](https://github.com/movahhedi)

### Developments and Copyrights

To build it for development, you need these:
- [NPM](https://www.npmjs.com/)
- [SASS](https://sass-lang.com/install)
- [Bootstrap 4.6.1](https://www.npmjs.com/package/bootstrap/v/4.6.1) (PMA doesn't support Bootstrap 5)

The icons used in Blueberry is from [Fluency (Fluent UI) icon set](https://github.com/microsoft/fluentui-system-icons) by Microsoft (Thanks to [Icons8](https://icons8.com/))

My custom [jQuery UI v1.13.1](http://jqueryui.com) CSS is also used. Check it out [here](http://jqueryui.com/themeroller/?scope=&folderName=smoothness&bgImgOpacityError=30&bgImgOpacityHighlight=30&bgImgOpacityActive=40&bgImgOpacityHover=40&bgImgOpacityDefault=20&bgImgOpacityContent=20&bgImgOpacityHeader=15&cornerRadiusShadow=8px&offsetLeftShadow=-2px&offsetTopShadow=-2px&thicknessShadow=2px&opacityShadow=30&bgImgOpacityShadow=0&bgTextureShadow=flat&bgColorShadow=%233a3a56&opacityOverlay=30&bgImgOpacityOverlay=50&bgTextureOverlay=flat&bgColorOverlay=%235b5b5b&iconColorError=%23ffffff&fcError=%23ffffff&borderColorError=%23ca0b0b&bgTextureError=flat&bgColorError=%23ca0b0b&iconColorHighlight=%23ffffff&fcHighlight=%23ffffff&borderColorHighlight=%230072e6&bgTextureHighlight=flat&bgColorHighlight=%230072e6&iconColorActive=%2338bdf8&fcActive=%2338bdf8&borderColorActive=%23096ac8&bgTextureActive=flat&bgColorActive=%231e1e2a&iconColorHover=%2338bdf8&fcHover=%2338bdf8&borderColorHover=%23222222&bgTextureHover=flat&bgColorHover=%232c2c3d&iconColorDefault=%2338bdf8&fcDefault=%23d9d9d9&borderColorDefault=%231e1e2a&bgTextureDefault=flat&bgColorDefault=%232c2c3d&iconColorContent=%2338bdf8&fcContent=%23d9d9d9&borderColorContent=%231e1e2a&bgTextureContent=flat&bgColorContent=%231e1e2a&iconColorHeader=%23e2e8f0&fcHeader=%23e2e8f0&borderColorHeader=%231e1e2a&bgTextureHeader=flat&bgColorHeader=%230072e6&cornerRadius=10px&fwDefault=bold&fsDefault=1em&ffDefault=%22Segoe%20UI%22%2C%20%22Segoe%20Pro%22%2C%20Roboto%2C%20Verdana%2C%20sans-serif)

### Any Ideas?

Tell me your ideas as an Issue at [https://github.com/movahhedi/blueberry-pma-theme/issues](https://github.com/movahhedi/blueberry-pma-theme/issues)

### CODE REVIEW

**Comment by williamdes** [comment]
Hi!
Thank you for this new theme! 

> PMA doesn't support Bootstrap 5


I am not sure about that, @MauricioFauth do you have some feedback?

**Comment by movahhedi** [comment]
At first I used Bootstrap 5 to compile and edit Shahab theme, but there were errors and unintended changes compared to `pmahomme`. I found out Bootstrap 5 had at least a few changes that phpMyAdmin doesn't support [yet].
Such as:
- Changing direction-specific values of `left, right` to direction-neutral values `start, end`, and thus change of some classnames such as `ml-2` (margin-left) to `ms-2` (margin-inline-start)
- Changes in media queries and function names
- Removing the `sr-only` class (screen-readers-only)

Plus, I suggest changing all the SCSS variables of `$left`, `$right` to direction-neutral names of `$direction-start`, `$direction-end` (used in Shahab too) and gradually expanding it to the phpMyAdmin core.

**Comment by williamdes** [comment]
I love the new name!

**Comment by movahhedi** [comment]
I renamed the theme from Shahab to Blueberry.

**Comment by movahhedi** [comment]
Thanks.
Added a screenshot of the database page.

**Comment by movahhedi** [comment]
I think Blueberry 1.0.1 is quite ready for release now.
I created [a release](https://github.com/movahhedi/blueberry-pma-theme/releases/tag/blueberry-1.0.1) for it too.
Do you agree? @williamdes @MauricioFauth

**Comment by ibennetch** [comment]
This looks very nice. I agree that we should incorporate this to phpMyAdmin. Thanks.

**Comment by nidhal0105** [comment]
I am using it with version 5.1.3
There is a little issue ^^ the "Designer" and "Central colums" disappear from the navbar
when i go with : localhost/phpmyadmin/index.php?route=%2Fdatabase%2Fstructure&db=<dbname> they show up for a sec but they desappear whenever i click on anything :(
you need to add them to The structure below where there is `/database/` instead of  `%2Fdatabase%2F`
localhost/phpmyadmin/index.php?route=/database/structure&server=1&db=<dbname>

I liked your theme a lot it's awsome but since i use a lot of relations and the Designier

**Comment by williamdes** [comment]
> I am using it with version 5.1.3 There is a little issue ^^ the "Designer" and "Central colums" disappear from the navbar when i go with : localhost/phpmyadmin/index.php?route=%2Fdatabase%2Fstructure&db= they show up for a sec but they desappear whenever i click on anything :( you need to add them to The structure below where there is `/database/` instead of `%2Fdatabase%2F` localhost/phpmyadmin/index.php?route=/database/structure&server=1&db=
> 
> I liked your theme a lot it's awsome but since i use a lot of relations and the Designier i need to add %2F every time manualy

Please open an issue on the phpMyAdmin repository for this because I do not think it is related to the theme :)
Also I would recommend you to test 5.2.0 because no more 5.1 versions will be done normally, 5.2 is the new stable

**Comment by ibennetch** [comment]
I'd love to release this for 5.2 if it could be updated.

**Comment by movahhedi** [comment]
Aye, aye, captain. Will do.

**Comment by movahhedi** [comment]
I made some changes to make Blueberry compatible with PMA v5.2 + The Bootstrap version is now v5.2.2.
Any thoughts? @ibennetch @williamdes

**Comment by ibennetch** [comment]
Personally, I really like this theme. The icons are bold and the whole thing is appropriately dark.

Anyway, I'm merging and releasing it. Thank you for your contribution and for the fixes.

**Comment by movahhedi** [comment]
Hello again.
Just got reminded of this theme. Is there any steps needed to be taken to add Blueberry to the core?
https://github.com/phpmyadmin/phpmyadmin/tree/master/public/themes

**Pull request merged**
