### PR TITLE
New theme darkwolfbootstrap for phpmyadmin 5.2

### PR DESCRIPTION
**Pull request by SteppenWolf68**
Hi @williamdes, @MauricioFauth, @ibennetch 

I share the new darkwolfbootstrap theme for phpmyadmin 5.2.
I hope you like it and once it passes the revision, it can be shared to download in phpmyadmin.net, any details in the changes let me know so I can correct them as soon as possible, greetings...

[darkwolfbootstrap.zip](https://github.com/phpmyadmin/themes/files/8944768/darkwolfbootstrap.zip)

screen

### CODE REVIEW

**Comment by TheCalypso** [comment]
Hello, thank you for the work you do. I allow myself to write to you because I have just found a small problem in the theme. I can't expand the Description category window.

image

Have a good day !

**Comment by SteppenWolf68** [comment]
Hi @ibennetch, @TheCalypso

I hope you are well, attached zip with updated darkbootstrap theme. correction of minimal details in terms of backgrounds and letter colors as well as margins. I hope I have corrected @TheCalypso's request
I appreciate your comments to be able to resolve any details of the darkwolfbootstrap theme, greetings

[darkwolfbootstrap.zip](https://github.com/phpmyadmin/themes/files/8987428/darkwolfbootstrap.zip)

**Comment by TheCalypso** [comment]
Hello @SteppenWolf68 , thank you very much for your answer and your solution so fast! Everything is good on my side, I continue to do tests on what I usually use in order to be able to give you feedback if necessary. Very good work !

**Comment by williamdes** [comment]
Hi @SteppenWolf68 
Thank you for the update !
I am not sure why it was created on `QA_3_3` but anyway I (or someone else) will do my best merging this into master branch

**Comment by SteppenWolf68** [comment]
> Hi @SteppenWolf68 Thank you for the update ! I am not sure why it was created on `QA_3_3` but anyway I (or someone else) will do my best merging this into master branch

Hi @williamdes 

Actually I didn't know how to create a new pull, when I tried it only that option allowed me, I appreciate reviewing the new darkwolfbootstrap theme for phpMyAdmin 5.2 and if everything is correct it can be downloaded from phpmyadmin.net/themes for those who want it

**Comment by bagou4502** [comment]
I see a small  bug with your theme we can t go on left/right when the table is too long.

image

This bar is not present on your theme.

**Comment by SteppenWolf68** [comment]
> I see a small bug with your theme we can t go on left/right when the table is too long.
> 
> image
> 
> This bar is not present on your theme.

Hi @bagou4502

if you need the scrollbars just remove this in theme.css:

body {
-ms-overflow-style: none; /* for Internet Explorer, Edge / scrollbar-width: none; / for Firefox / overflow-y: scroll;
}
body::-webkit-scrollbar {
display: none; / for Chrome, Safari, and Opera */
}

**Comment by SoGCuicui** [comment]
Hi, I also have a small issue:
Untitled2

**Comment by SteppenWolf68** [comment]
> I also have a small issue

Hi @SoGCuicui 

Thanks for looking at this detail, in theme.css find >> select.pageselector and change > display: block to > display: inline and remove > margin-left: 12px !important
that solves the problem,

attached updated zip file

[darkwolfbootstrap.zip](https://github.com/phpmyadmin/themes/files/9086465/darkwolfbootstrap.zip)

cheers

**Pull request closed without merging**
