### PR TITLE
Update Fallen theme for 4.8

### PR DESCRIPTION
**Pull request by KiitoX**

### CODE REVIEW

**Comment by HanFox** [comment]
@KiitoX you appear to have missed doing the necessary changes in [css/designer.css.php](https://github.com/KiitoX/themes/blob/b3a4762c321168ff4e42103f252427e5dbb9d39b/fallen/css/designer.css.php)

Besides that this seems to work great. Thanks.

**Comment by KiitoX** [comment]
You're totally right, that must've gotten lost somewhere on the way. Thanks a bunch ^-^

**Comment by mauriciofauth** [comment]
Merged, thanks for your contribution!

**Comment by ibennetch** [comment]
I've just released Fallen 0.7 at https://www.phpmyadmin.net/themes/

Thanks for your contribution!

**Pull request merged**
