### PR TITLE
I would like this topic to be shared - DarkWolf Theme Phpmyadmin 5.0/5.0.4 

### PR DESCRIPTION
**Pull request by SteppenWolf68**

### CODE REVIEW

**Comment by SteppenWolf68** [comment]
I would like this topic to be shared

**Comment by mauriciofauth** [comment]
Hi @SteppenWolf68. Thank you for your interest in sharing your theme.

Looks like something went wrong with your pull request. Your theme files are not included.

Do you need some help?

**Comment by SteppenWolf68** [comment]
> Hi @SteppenWolf68. Thank you for your interest in sharing your theme.
> 
> Looks like something went wrong with your pull request. Your theme files are not included.
> 
> Do you need some help?

Hi @mauriciofauth. Thanks for contacting me, I
[darkwolf.zip](https://github.com/phpmyadmin/themes/files/5541353/darkwolf.zip)
 send the darkwolf theme files

**Comment by ibennetch** [comment]
In darkwolf/theme.json, I assume you meant for `"name": "darwolf",` to be "dar**k**worf", correct?

**Comment by ibennetch** [comment]
This looks good to me, although when I switch to version 5.1 (after increasing the supported version in themes.json), I see a bit of trouble with the menu:
image

It would be nice if we could support 5.1 with this theme, but I'm not immediately sure what the problem is there.

Since we can't easily merge a zip file, I've attached your work to the git repository at https://github.com/ibennetch/themes/tree/darkwolf and eventually it will be merged here in the main one.

**Comment by ibennetch** [comment]
Also, the lines `"description": "Default phpMyAdmin theme"` and `"author": "phpMyAdmin developers"` aren't so great; would you like us to put your own name or alias as the author? The description can easily be made as "Another dark theme for phpMyAdmin" or something like that.

**Comment by ibennetch** [comment]
I imagine the files img/b_group.png.bak and img/sprites.png.bak can be safely removed from this upload?

**Comment by muhviehstah** [comment]
tried the upload version (wrong extension .. its a rar) 

looks very nice on first look. :)

**Comment by ibennetch** [comment]
The menubar problem is related to phpmyadmin/phpmyadmin#15775, so that's easy to fix.

I can release a 5.0 version of this and then fix the menu bar for 5.1 compatibility.

**Comment by SteppenWolf68** [comment]
> tried the upload version (wrong extension .. its a rar)
> 
> looks very nice on first look. :)

Hi, upload is update, tried now. :)

**Comment by SteppenWolf68** [comment]
> The menubar problem is related to [phpmyadmin/phpmyadmin#15775](https://github.com/phpmyadmin/phpmyadmin/pull/15775), so that's easy to fix.
> 
> I can release a 5.0 version of this and then fix the menu bar for 5.1 compatibility.

I will appreciate your help for compatibility

**Comment by ibennetch** [comment]
Yeah, we have a few other themes with the same compatibility problem for
5.1, so we will take a look at it.

**Comment by ibennetch** [comment]
darkwolf has now been published at https://www.phpmyadmin.net/themes/

**Pull request closed without merging**
