### PR TITLE
Adjusting theme.css to fix colors/buttons on some tabs

### PR DESCRIPTION
**Pull request by Simushy**
Fixed:
-import: default arrows showing on hover on buttons, toggle switch color when on, narrowed select on "Format-specific options", select file button color on hover
-designer: table header color from white to default bg color, some fields appearing white->changed to blue

### CODE REVIEW

**Review by williamdes — CHANGES_REQUESTED** [review]
Can you push the fixes to the source files in https://github.com/phpmyadmin/themes/tree/master/blueberry/scss ?

**Comment by Simushy** [comment]
> Can you push the fixes to the source files in https://github.com/phpmyadmin/themes/tree/master/blueberry/scss ?

unfortunately fixes i did in scss files don't work as expected, i'd have to remove all changed attributes from theme.css and insert them in the appropriate files

**Comment by williamdes** [comment]
> > Can you push the fixes to the source files in https://github.com/phpmyadmin/themes/tree/master/blueberry/scss ?
> 
> unfortunately fixes i did in scss files don't work as expected, i'd have to remove all changed attributes from theme.css and insert them in the appropriate files. if that's ok i can do it in the evening if it's needed

Well you really need to get the .scss files modified one way or another because it causes build and trust issues to have compressed css files ;)

**Comment by Simushy** [comment]
I'd stoll have to remove attributes from css file that interfere with fixes in scss files

**Pull request closed without merging**
