### PR TITLE
#1646 Metro theme design update

### PR DESCRIPTION
**Pull request by madhuracj**
Signed-off-by: Madhura Jayaratne <madhura.cj@gmail.com>

### CODE REVIEW

**Comment by lem9** [comment]
Madhura,
is this work in progress? Does it answer to all of the issues mentionned in the RFE ?

**Comment by madhuracj** [comment]
This is not work in progress. Fixes all issue except for a change in collapse-all icon

**Comment by madhuracj** [comment]
https://github.com/madhuracj/themes/commit/a72ecf354dd43212f389c137124ee665a2b973b6 fixes another similar instance.

**Comment by lem9** [comment]
Thanks. Maybe we should wait for the outcome of
https://sourceforge.net/p/phpmyadmin/feature-requests/1648/
https://sourceforge.net/p/phpmyadmin/feature-requests/1649/

before releasing a new version of this theme?

**Comment by madhuracj** [comment]
Yes, that makes sense.

**Pull request merged**
