### PR TITLE
New update BooDark v1.1.0 - pma 5.2

### PR DESCRIPTION
**Pull request by adorade**
**Changes**

- Fix some color styles
- New color schemes: `cyan` (main), `teal`, `nord` and `orange`

Fixes: #100

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
Thank you !
Your theme is very good quality 💯

**Comment by adorade** [comment]
Thanks for appreciation!

**Comment by adorade** [comment]
Why does the review take so long?

**Comment by williamdes** [comment]
> Why does the review take so long?

Well, actually releases rely on @ibennetch
that's why it's still pending :/

**Comment by williamdes** [comment]
Hi @adorade 

I just found out this bug
On drop tables, the query is not readable due to the text color.

image

Is it fixed now ?

**Comment by adorade** [comment]
@williamdes I think so, but I'll double check later to be sure

**Comment by adorade** [comment]
Solved in BooDark v1.1.0: https://github.com/adorade/boodark/issues/35
What version of the BooDark theme are you using?

**Comment by adorade** [comment]
@ibennetch can you review this PR? Thank you!

**Comment by williamdes** [comment]
> Solved in BooDark v1.1.0: [adorade/boodark#35](https://github.com/adorade/boodark/issues/35) What version of the BooDark theme are you using?

Probably the (old) latest version :/
Sorry about that, I will update my setup with the version in this PR

**Comment by ibennetch** [comment]
I think the way to handle this is for me to create a different release for each color scheme.

For phpMyAdmin version 6.0, we now have a "colorModes" option (you can see it best in 'metro' theme, https://github.com/phpmyadmin/phpmyadmin/blob/daa252ba42cca3ce8b37062e6916db923a91c9bb/public/themes/metro/theme.json#L8 and throughout the theme), which may be very helpful to you.

**Comment by ibennetch** [comment]
This theme looks great! I love the color options. I've published the releases to our theme page.

**Comment by adorade** [comment]
> For phpMyAdmin version 6.0, we will have a "colorModes" option (you can see it best in 'metro' theme, https://github.com/phpmyadmin/phpmyadmin/blob/daa252ba42cca3ce8b37062e6916db923a91c9bb/public/themes/metro/theme.json#L8 and throughout the theme), which may be very helpful to you.

@ibennetch 
I have already implemented **colorModes** in **BooDark v2** for pma v6, I will review the latest changes in pma source code next week and I will open an issue or PR only for testing purpose.

**Pull request merged**
