### PR TITLE
Upload new theme Black carde by @AppCarde

### PR DESCRIPTION
**Pull request by williamdes**
Replaces: #71

by @AppCarde

In reply to https://github.com/phpmyadmin/themes/pull/64#issuecomment-1064132163

### CODE REVIEW

**Comment by AppCarde** [comment]
BlackCarde
for PhpMyAdmin 5.x
[BlackCarde.zip](https://github.com/phpmyadmin/themes/files/8457789/BlackCarde.zip)

**Comment by williamdes** [comment]
Hi @AppCarde

Do you have new fixes for your theme ?

**Comment by AppCarde** [comment]
Hi, Dear. Soon. I'd like to prepare myself for the new version of
PhpMyAdmin, which I have already downloaded and am adapting.

Em dom., 1 de jan. de 2023 às 04:22, William Desportes <
***@***.***> escreveu:

**Comment by williamdes** [comment]
Hi @AppCarde
Is your update ready?

**Comment by AppCarde** [comment]
In proccess


William Desportes ***@***.***> escreveu no dia domingo,
14/05/2023 à(s) 05:18:

**Comment by williamdes** [comment]
Closing it, let us know when it's necessary to open one for you, feel free to re open one yourself too

**Pull request closed without merging**
